// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: AdvancedColorPicker.GradientBackground2D
#include "AdvancedColorPicker/GradientBackground2D.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Begin forward declares
// Forward declaring namespace: AdvancedColorPicker
namespace AdvancedColorPicker {
  // Forward declaring type: Slider2D
  class Slider2D;
}
// Completed forward declares
// Type namespace: AdvancedColorPicker
namespace AdvancedColorPicker {
  // Forward declaring type: GradientBox
  class GradientBox;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::AdvancedColorPicker::GradientBox);
DEFINE_IL2CPP_ARG_TYPE(::AdvancedColorPicker::GradientBox*, "AdvancedColorPicker", "GradientBox");
// Type namespace: AdvancedColorPicker
namespace AdvancedColorPicker {
  // Size: 0xF9
  #pragma pack(push, 1)
  // Autogenerated type: AdvancedColorPicker.GradientBox
  // [TokenAttribute] Offset: FFFFFFFF
  // [RequireComponent] Offset: 71D448
  // [ExecuteInEditMode] Offset: FFFFFFFF
  class GradientBox : public ::AdvancedColorPicker::GradientBackground2D {
    public:
    #ifdef USE_CODEGEN_FIELDS
    public:
    #else
    #ifdef CODEGEN_FIELD_ACCESSIBILITY
    CODEGEN_FIELD_ACCESSIBILITY:
    #else
    protected:
    #endif
    #endif
    // private AdvancedColorPicker.Slider2D slider
    // Size: 0x8
    // Offset: 0xF0
    ::AdvancedColorPicker::Slider2D* slider;
    // Field size check
    static_assert(sizeof(::AdvancedColorPicker::Slider2D*) == 0x8);
    // private System.Boolean dontListenToSlider
    // Size: 0x1
    // Offset: 0xF8
    bool dontListenToSlider;
    // Field size check
    static_assert(sizeof(bool) == 0x1);
    public:
    // Get instance field reference: private AdvancedColorPicker.Slider2D slider
    ::AdvancedColorPicker::Slider2D*& dyn_slider();
    // Get instance field reference: private System.Boolean dontListenToSlider
    bool& dyn_dontListenToSlider();
    // private System.Void UpdatePickerValues(System.Single xValue, System.Single yValue)
    // Offset: 0xE2067C
    void UpdatePickerValues(float xValue, float yValue);
    // protected override System.Boolean get_InverseX()
    // Offset: 0xE20284
    // Implemented from: AdvancedColorPicker.GradientBackground2D
    // Base method: System.Boolean GradientBackground2D::get_InverseX()
    bool get_InverseX();
    // protected override System.Boolean get_InverseY()
    // Offset: 0xE202A0
    // Implemented from: AdvancedColorPicker.GradientBackground2D
    // Base method: System.Boolean GradientBackground2D::get_InverseY()
    bool get_InverseY();
    // public System.Void .ctor()
    // Offset: 0xE208A8
    // Implemented from: AdvancedColorPicker.GradientBackground2D
    // Base method: System.Void GradientBackground2D::.ctor()
    // Base method: System.Void GraphicalColorTypeComponent::.ctor()
    // Base method: System.Void GraphicalColorComponent::.ctor()
    // Base method: System.Void MaskableGraphic::.ctor()
    // Base method: System.Void Graphic::.ctor()
    // Base method: System.Void UIBehaviour::.ctor()
    // Base method: System.Void MonoBehaviour::.ctor()
    // Base method: System.Void Behaviour::.ctor()
    // Base method: System.Void Component::.ctor()
    // Base method: System.Void Object::.ctor()
    // Base method: System.Void Object::.ctor()
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static GradientBox* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::AdvancedColorPicker::GradientBox::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<GradientBox*, creationType>()));
    }
    // protected override System.Void Awake()
    // Offset: 0xE202BC
    // Implemented from: UnityEngine.EventSystems.UIBehaviour
    // Base method: System.Void UIBehaviour::Awake()
    void Awake();
    // protected override System.Void OnEnable()
    // Offset: 0xE20320
    // Implemented from: AdvancedColorPicker.GraphicalColorComponent
    // Base method: System.Void GraphicalColorComponent::OnEnable()
    void OnEnable();
    // protected override System.Void OnDisable()
    // Offset: 0xE204D8
    // Implemented from: AdvancedColorPicker.GraphicalColorComponent
    // Base method: System.Void GraphicalColorComponent::OnDisable()
    void OnDisable();
    // protected override System.Void DisplayNewColor()
    // Offset: 0xE20758
    // Implemented from: AdvancedColorPicker.GradientBackground2D
    // Base method: System.Void GradientBackground2D::DisplayNewColor()
    void DisplayNewColor();
  }; // AdvancedColorPicker.GradientBox
  #pragma pack(pop)
  static check_size<sizeof(GradientBox), 248 + sizeof(bool)> __AdvancedColorPicker_GradientBoxSizeCheck;
  static_assert(sizeof(GradientBox) == 0xF9);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: AdvancedColorPicker::GradientBox::UpdatePickerValues
// Il2CppName: UpdatePickerValues
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (AdvancedColorPicker::GradientBox::*)(float, float)>(&AdvancedColorPicker::GradientBox::UpdatePickerValues)> {
  static const MethodInfo* get() {
    static auto* xValue = &::il2cpp_utils::GetClassFromName("System", "Single")->byval_arg;
    static auto* yValue = &::il2cpp_utils::GetClassFromName("System", "Single")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(AdvancedColorPicker::GradientBox*), "UpdatePickerValues", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{xValue, yValue});
  }
};
// Writing MetadataGetter for method: AdvancedColorPicker::GradientBox::get_InverseX
// Il2CppName: get_InverseX
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<bool (AdvancedColorPicker::GradientBox::*)()>(&AdvancedColorPicker::GradientBox::get_InverseX)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(AdvancedColorPicker::GradientBox*), "get_InverseX", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: AdvancedColorPicker::GradientBox::get_InverseY
// Il2CppName: get_InverseY
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<bool (AdvancedColorPicker::GradientBox::*)()>(&AdvancedColorPicker::GradientBox::get_InverseY)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(AdvancedColorPicker::GradientBox*), "get_InverseY", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: AdvancedColorPicker::GradientBox::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: AdvancedColorPicker::GradientBox::Awake
// Il2CppName: Awake
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (AdvancedColorPicker::GradientBox::*)()>(&AdvancedColorPicker::GradientBox::Awake)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(AdvancedColorPicker::GradientBox*), "Awake", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: AdvancedColorPicker::GradientBox::OnEnable
// Il2CppName: OnEnable
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (AdvancedColorPicker::GradientBox::*)()>(&AdvancedColorPicker::GradientBox::OnEnable)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(AdvancedColorPicker::GradientBox*), "OnEnable", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: AdvancedColorPicker::GradientBox::OnDisable
// Il2CppName: OnDisable
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (AdvancedColorPicker::GradientBox::*)()>(&AdvancedColorPicker::GradientBox::OnDisable)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(AdvancedColorPicker::GradientBox*), "OnDisable", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: AdvancedColorPicker::GradientBox::DisplayNewColor
// Il2CppName: DisplayNewColor
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (AdvancedColorPicker::GradientBox::*)()>(&AdvancedColorPicker::GradientBox::DisplayNewColor)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(AdvancedColorPicker::GradientBox*), "DisplayNewColor", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
