// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: AdvancedColorPicker.SliderCircle2D
#include "AdvancedColorPicker/SliderCircle2D.hpp"
// Including type: UnityEngine.Events.UnityEvent`2
#include "UnityEngine/Events/UnityEvent_2.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
// Completed includes
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::AdvancedColorPicker::SliderCircle2D::SliderCircleEvent);
DEFINE_IL2CPP_ARG_TYPE(::AdvancedColorPicker::SliderCircle2D::SliderCircleEvent*, "AdvancedColorPicker", "SliderCircle2D/SliderCircleEvent");
// Type namespace: AdvancedColorPicker
namespace AdvancedColorPicker {
  // WARNING Size may be invalid!
  // Autogenerated type: AdvancedColorPicker.SliderCircle2D/AdvancedColorPicker.SliderCircleEvent
  // [TokenAttribute] Offset: FFFFFFFF
  class SliderCircle2D::SliderCircleEvent : public ::UnityEngine::Events::UnityEvent_2<float, float> {
    public:
    // public System.Void .ctor()
    // Offset: 0x5BC9D0
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static SliderCircle2D::SliderCircleEvent* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::AdvancedColorPicker::SliderCircle2D::SliderCircleEvent::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<SliderCircle2D::SliderCircleEvent*, creationType>()));
    }
  }; // AdvancedColorPicker.SliderCircle2D/AdvancedColorPicker.SliderCircleEvent
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: AdvancedColorPicker::SliderCircle2D::SliderCircleEvent::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
