// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: System.ValueType
#include "System/ValueType.hpp"
// Including type: Steamworks.ICallbackData
#include "Steamworks/ICallbackData.hpp"
// Including type: Steamworks.DenyReason
#include "Steamworks/DenyReason.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: Steamworks
namespace Steamworks {
  // Forward declaring type: CallbackType
  struct CallbackType;
}
// Completed forward declares
// Type namespace: Steamworks.Data
namespace Steamworks::Data {
  // Forward declaring type: GSClientKick_t
  struct GSClientKick_t;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(::Steamworks::Data::GSClientKick_t, "Steamworks.Data", "GSClientKick_t");
// Type namespace: Steamworks.Data
namespace Steamworks::Data {
  // Size: 0xC
  #pragma pack(push, 1)
  // WARNING Layout: Sequential may not be correctly taken into account!
  // Autogenerated type: Steamworks.Data.GSClientKick_t
  // [TokenAttribute] Offset: FFFFFFFF
  struct GSClientKick_t/*, public ::System::ValueType, public ::Steamworks::ICallbackData*/ {
    public:
    public:
    // System.UInt64 SteamID
    // Size: 0x8
    // Offset: 0x0
    uint64_t SteamID;
    // Field size check
    static_assert(sizeof(uint64_t) == 0x8);
    // Steamworks.DenyReason DenyReason
    // Size: 0x4
    // Offset: 0x8
    ::Steamworks::DenyReason DenyReason;
    // Field size check
    static_assert(sizeof(::Steamworks::DenyReason) == 0x4);
    public:
    // Creating value type constructor for type: GSClientKick_t
    constexpr GSClientKick_t(uint64_t SteamID_ = {}, ::Steamworks::DenyReason DenyReason_ = {}) noexcept : SteamID{SteamID_}, DenyReason{DenyReason_} {}
    // Creating interface conversion operator: operator ::System::ValueType
    operator ::System::ValueType() noexcept {
      return *reinterpret_cast<::System::ValueType*>(this);
    }
    // Creating interface conversion operator: operator ::Steamworks::ICallbackData
    operator ::Steamworks::ICallbackData() noexcept {
      return *reinterpret_cast<::Steamworks::ICallbackData*>(this);
    }
    // Get static field: static public System.Int32 _datasize
    static int _get__datasize();
    // Set static field: static public System.Int32 _datasize
    static void _set__datasize(int value);
    // Get instance field reference: System.UInt64 SteamID
    uint64_t& dyn_SteamID();
    // Get instance field reference: Steamworks.DenyReason DenyReason
    ::Steamworks::DenyReason& dyn_DenyReason();
    // public Steamworks.CallbackType get_CallbackType()
    // Offset: 0xA52758
    ::Steamworks::CallbackType get_CallbackType();
    // static private System.Void .cctor()
    // Offset: 0xA52760
    static void _cctor();
  }; // Steamworks.Data.GSClientKick_t
  #pragma pack(pop)
  static check_size<sizeof(GSClientKick_t), 8 + sizeof(::Steamworks::DenyReason)> __Steamworks_Data_GSClientKick_tSizeCheck;
  static_assert(sizeof(GSClientKick_t) == 0xC);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: Steamworks::Data::GSClientKick_t::get_CallbackType
// Il2CppName: get_CallbackType
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::Steamworks::CallbackType (Steamworks::Data::GSClientKick_t::*)()>(&Steamworks::Data::GSClientKick_t::get_CallbackType)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Steamworks::Data::GSClientKick_t), "get_CallbackType", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Steamworks::Data::GSClientKick_t::_cctor
// Il2CppName: .cctor
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (*)()>(&Steamworks::Data::GSClientKick_t::_cctor)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Steamworks::Data::GSClientKick_t), ".cctor", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
