// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: Steamworks.SteamNetworkingUtils
#include "Steamworks/SteamNetworkingUtils.hpp"
// Including type: Steamworks.Data.SteamRelayNetworkStatus_t
#include "Steamworks/Data/SteamRelayNetworkStatus_t.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: Action`1<T>
  template<typename T>
  class Action_1;
}
// Completed forward declares
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::Steamworks::SteamNetworkingUtils::$$c);
DEFINE_IL2CPP_ARG_TYPE(::Steamworks::SteamNetworkingUtils::$$c*, "Steamworks", "SteamNetworkingUtils/<>c");
// Type namespace: Steamworks
namespace Steamworks {
  // Size: 0x10
  #pragma pack(push, 1)
  // Autogenerated type: Steamworks.SteamNetworkingUtils/Steamworks.<>c
  // [TokenAttribute] Offset: FFFFFFFF
  // [CompilerGeneratedAttribute] Offset: FFFFFFFF
  class SteamNetworkingUtils::$$c : public ::Il2CppObject {
    public:
    // Get static field: static public readonly Steamworks.SteamNetworkingUtils/Steamworks.<>c <>9
    static ::Steamworks::SteamNetworkingUtils::$$c* _get_$$9();
    // Set static field: static public readonly Steamworks.SteamNetworkingUtils/Steamworks.<>c <>9
    static void _set_$$9(::Steamworks::SteamNetworkingUtils::$$c* value);
    // Get static field: static public System.Action`1<Steamworks.Data.SteamRelayNetworkStatus_t> <>9__3_0
    static ::System::Action_1<::Steamworks::Data::SteamRelayNetworkStatus_t>* _get_$$9__3_0();
    // Set static field: static public System.Action`1<Steamworks.Data.SteamRelayNetworkStatus_t> <>9__3_0
    static void _set_$$9__3_0(::System::Action_1<::Steamworks::Data::SteamRelayNetworkStatus_t>* value);
    // static private System.Void .cctor()
    // Offset: 0x5C9C60
    static void _cctor();
    // public System.Void .ctor()
    // Offset: 0x1DD400
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static SteamNetworkingUtils::$$c* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::Steamworks::SteamNetworkingUtils::$$c::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<SteamNetworkingUtils::$$c*, creationType>()));
    }
    // System.Void <InstallCallbacks>b__3_0(Steamworks.Data.SteamRelayNetworkStatus_t x)
    // Offset: 0x5C7C30
    void $InstallCallbacks$b__3_0(::Steamworks::Data::SteamRelayNetworkStatus_t x);
  }; // Steamworks.SteamNetworkingUtils/Steamworks.<>c
  #pragma pack(pop)
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: Steamworks::SteamNetworkingUtils::$$c::_cctor
// Il2CppName: .cctor
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (*)()>(&Steamworks::SteamNetworkingUtils::$$c::_cctor)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Steamworks::SteamNetworkingUtils::$$c*), ".cctor", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Steamworks::SteamNetworkingUtils::$$c::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: Steamworks::SteamNetworkingUtils::$$c::$InstallCallbacks$b__3_0
// Il2CppName: <InstallCallbacks>b__3_0
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (Steamworks::SteamNetworkingUtils::$$c::*)(::Steamworks::Data::SteamRelayNetworkStatus_t)>(&Steamworks::SteamNetworkingUtils::$$c::$InstallCallbacks$b__3_0)> {
  static const MethodInfo* get() {
    static auto* x = &::il2cpp_utils::GetClassFromName("Steamworks.Data", "SteamRelayNetworkStatus_t")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Steamworks::SteamNetworkingUtils::$$c*), "<InstallCallbacks>b__3_0", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{x});
  }
};
