// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: System.ValueType
#include "System/ValueType.hpp"
// Including type: UnityEngine.Vector3
#include "UnityEngine/Vector3.hpp"
// Including type: UnityEngine.Quaternion
#include "UnityEngine/Quaternion.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: Normal::Realtime
namespace Normal::Realtime {
  // Forward declaring type: TimelineEntry`1<T>
  template<typename T>
  class TimelineEntry_1;
}
// Completed forward declares
// Type namespace: Normal.Realtime
namespace Normal::Realtime {
  // Forward declaring type: StandardTransformFrame
  struct StandardTransformFrame;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(::Normal::Realtime::StandardTransformFrame, "Normal.Realtime", "StandardTransformFrame");
// Type namespace: Normal.Realtime
namespace Normal::Realtime {
  // Size: 0x28
  #pragma pack(push, 1)
  // WARNING Layout: Sequential may not be correctly taken into account!
  // Autogenerated type: Normal.Realtime.StandardTransformFrame
  // [TokenAttribute] Offset: FFFFFFFF
  // [IsReadOnlyAttribute] Offset: FFFFFFFF
  struct StandardTransformFrame/*, public ::System::ValueType*/ {
    public:
    public:
    // public readonly UnityEngine.Vector3 position
    // Size: 0xC
    // Offset: 0x0
    ::UnityEngine::Vector3 position;
    // Field size check
    static_assert(sizeof(::UnityEngine::Vector3) == 0xC);
    // public readonly UnityEngine.Quaternion rotation
    // Size: 0x10
    // Offset: 0xC
    ::UnityEngine::Quaternion rotation;
    // Field size check
    static_assert(sizeof(::UnityEngine::Quaternion) == 0x10);
    // public readonly UnityEngine.Vector3 scale
    // Size: 0xC
    // Offset: 0x1C
    ::UnityEngine::Vector3 scale;
    // Field size check
    static_assert(sizeof(::UnityEngine::Vector3) == 0xC);
    public:
    // Creating value type constructor for type: StandardTransformFrame
    constexpr StandardTransformFrame(::UnityEngine::Vector3 position_ = {}, ::UnityEngine::Quaternion rotation_ = {}, ::UnityEngine::Vector3 scale_ = {}) noexcept : position{position_}, rotation{rotation_}, scale{scale_} {}
    // Creating interface conversion operator: operator ::System::ValueType
    operator ::System::ValueType() noexcept {
      return *reinterpret_cast<::System::ValueType*>(this);
    }
    // Get instance field reference: public readonly UnityEngine.Vector3 position
    ::UnityEngine::Vector3& dyn_position();
    // Get instance field reference: public readonly UnityEngine.Quaternion rotation
    ::UnityEngine::Quaternion& dyn_rotation();
    // Get instance field reference: public readonly UnityEngine.Vector3 scale
    ::UnityEngine::Vector3& dyn_scale();
    // public System.Void .ctor(UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Vector3 scale)
    // Offset: 0xA734EC
    // ABORTED: conflicts with another method.  StandardTransformFrame(::UnityEngine::Vector3 position, ::UnityEngine::Quaternion rotation, ::UnityEngine::Vector3 scale);
    // static public Normal.Realtime.StandardTransformFrame Interpolate(Normal.Realtime.TimelineEntry`1<Normal.Realtime.StandardTransformFrame> a, Normal.Realtime.TimelineEntry`1<Normal.Realtime.StandardTransformFrame> b, System.Single t)
    // Offset: 0xA73510
    static ::Normal::Realtime::StandardTransformFrame Interpolate(::Normal::Realtime::TimelineEntry_1<::Normal::Realtime::StandardTransformFrame>* a, ::Normal::Realtime::TimelineEntry_1<::Normal::Realtime::StandardTransformFrame>* b, float t);
  }; // Normal.Realtime.StandardTransformFrame
  #pragma pack(pop)
  static check_size<sizeof(StandardTransformFrame), 28 + sizeof(::UnityEngine::Vector3)> __Normal_Realtime_StandardTransformFrameSizeCheck;
  static_assert(sizeof(StandardTransformFrame) == 0x28);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: Normal::Realtime::StandardTransformFrame::StandardTransformFrame
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: Normal::Realtime::StandardTransformFrame::Interpolate
// Il2CppName: Interpolate
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::Normal::Realtime::StandardTransformFrame (*)(::Normal::Realtime::TimelineEntry_1<::Normal::Realtime::StandardTransformFrame>*, ::Normal::Realtime::TimelineEntry_1<::Normal::Realtime::StandardTransformFrame>*, float)>(&Normal::Realtime::StandardTransformFrame::Interpolate)> {
  static const MethodInfo* get() {
    static auto* a = &::il2cpp_utils::MakeGeneric(::il2cpp_utils::GetClassFromName("Normal.Realtime", "TimelineEntry`1"), ::std::vector<const Il2CppClass*>{::il2cpp_utils::GetClassFromName("Normal.Realtime", "StandardTransformFrame")})->byval_arg;
    static auto* b = &::il2cpp_utils::MakeGeneric(::il2cpp_utils::GetClassFromName("Normal.Realtime", "TimelineEntry`1"), ::std::vector<const Il2CppClass*>{::il2cpp_utils::GetClassFromName("Normal.Realtime", "StandardTransformFrame")})->byval_arg;
    static auto* t = &::il2cpp_utils::GetClassFromName("System", "Single")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Normal::Realtime::StandardTransformFrame), "Interpolate", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{a, b, t});
  }
};
